name: markdown-workspace
base: core22
version: '3.2.5.3'

title: SnapDock - Markdown Workspace
summary: Fast, clean Markdown editor
description: |
  SnapDock is a modern, distraction-free Markdown editor designed for people who want clarity, stability, and a writing environment that stays out of the way.

grade: stable
confinement: strict

apps:
  snapdock:
    command: snapdock --no-sandbox
    extensions: [gnome]
    desktop: meta/gui/snapdock.desktop
    plugs:
      - home
      - network
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - opengl
      - browser-support

parts:
  snapdock:
    plugin: dump
    source: ./dist/linux-unpacked
    stage-packages:
      - libasound2
      - libnss3
      - libnspr4
      - libxss1
      - libxtst6
      - libsecret-1-0

  desktop-integration:
    plugin: dump
    source: .
    organize:
      snapdock.desktop: meta/gui/snapdock.desktop
      assets/snapdock.png: meta/gui/snapdock.png
    prime:
      - meta/gui/snapdock.desktop
      - meta/gui/snapdock.png

plugs:
  shared-memory:
    private: true