name: SnapDock Release Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    #  - 121-release-pipeline-improvements // test branch here

permissions:
  contents: write
  id-token: write

jobs:
  # ---------------------------------------------------------
  # 1. Desktop Installers (Windows + Linux)
  # ---------------------------------------------------------
  desktop:
    name: Desktop Installers
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm ci

      - name: Build Desktop Release
        run: npm run build:release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desktop-${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.deb
            dist/*.AppImage
            dist/*.zip
            dist/*.dmg
          if-no-files-found: ignore

# attempted to make store releases automated via github and keep hitting issues
# i managed to automate on my server and its a good enough fix for now but will need to look at this again in the future

  # ---------------------------------------------------------
  # 4. GitHub Release
  # ---------------------------------------------------------
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [desktop]
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-assets/**
          generate_release_notes: true
